require_relative '../lib/music/music'
require_relative '../lib/music/genre'
require_relative '../lib/catalogue/catalogue'
require_relative '../lib/games/game'
require_relative '../lib/games/author'
require_relative '../lib/book/book'
require_relative '../lib/book/label'
